name: Add issues to project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/users/tokada1211/projects/2
          github-token: ${{ secrets.GIT_TOKEN }}


#name: Move new issues into Triage

#on:
#  issues:
#    types: [opened]

#jobs:
#  automate-project-columns:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: alex-page/github-project-automation-plus@v0.8.3
#        with:
#          project: "https://github.com/users/tokada1211/projects/2"
#          column: "PP"
#          repo-token: ${{ secrets.GIT_TOKEN }}

#name: Move new issues into プロジェクト名 (ここは好きに書いてください)
#on:
#  issues:
#    types: [opened]
#
#jobs:
#  automate-project-columns:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: alex-page/github-project-automation-plus@v0.3.0
#        with:
#          project: テストプロジェクト
#          column: Done
#          repo-token: ${{ secrets.GH_TOKEN }}
